services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: basirat_backend_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8011:8010
    env_file:
      - ./env/.local
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - basirat_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.local

volumes:
  basirat_data: