version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: basirat_web_prod
    command: /start
    volumes:
      - .:/app
      - /var/www/basirat/static:/app/static
      - /var/www/basirat/media:/app/media
    ports:
      - 8020:8000
    env_file:
      - ./env/.production
    depends_on:
      - db
  db:
    image: postgres:14

    volumes:
      - basirat_data_production:/var/lib/postgresql/data/
    env_file:
      - ./env/.production


volumes:
  basirat_data_production:
#  static_volume:
#  media_volume:
